---
# Install latest Tmux from sources with

- name: Check Tmux version.
  shell: set -o pipefail && tmux -V | egrep -o "[0-9]{1,}\.[0-9]{1,}"
  args:
    executable: /usr/bin/bash
  changed_when: false
  failed_when: false
  register: tmux_curr_ver

- name: DEBUG
  debug:
    var: tmux_curr_ver
  when: debug_mode is defined

- block:
    - name: Ensure Tmux dependencies are installed.
      apt:
        name:
          - libevent-dev
          - autoconf
          - automake
          - pkg-config
          - bison
        state: present
      become: true

    - name: Ensure the ~/build directory exists.
      file:
        path: ~/build
        state: directory
        mode: 0755
      become: false

    - name: Clone Tmux repository from GitHub.
      git:
        repo: https://github.com/tmux/tmux.git
        dest: ~/build/tmux
        version: "{{ tmux_ver | default('master') }}"
      become: false

    - name: Configure Tmux.
      shell: cd ~/build/tmux/ || exit 1; ./autogen.sh && ./configure

    - name: Compile and install Tmux.
      shell: cd ~/build/tmux/ && make clean && make && sudo make install

  when: tmux_curr_ver.rc !=0 or tmux_curr_ver.stdout | float < tmux_min_ver
