---
- name: Create user
  ansible.builtin.user:
    name: "{{ username_key_access }}"
    state: present
    system: false
    createhome: true
    home: "/home/{{ username_key_access }}"
    shell: /bin/bash
    password: "{{ userpass_key_access | password_hash('sha512') }}"
    update_password: on_create
    groups:   # add to group sudo to be able manage server
      - sudo
    append: true
  become: true

- name: Allow new user to have passwordless sudo.
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^{{ username_key_access }}"
    line: "{{ username_key_access }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
  become: true
