---
# Install Fzf

- name: Check Fzf version.
  shell: |
    set -o pipefail
    [ -f ~/.fzf.bash ] && source ~/.fzf.bash
    fzf --version | cut -d\  -f1
  args:
    executable: /usr/bin/bash
  changed_when: false
  failed_when: false
  register: fzf_curr_ver

- block:
    - name: Import a variable containing a Bash script to compare versions.
      include_role:
        name: version-compare-function

    - name: Compare installed and min Fzf versions.
      shell: |
        {{ ver_comp_func }}
        vercomp '{{ fzf_curr_ver.stdout }}' '{{ fzf_min_ver }}'
      args:
        executable: /usr/bin/bash
      changed_when: false
      failed_when: false
      register: compare_min_result
      when: >
        fzf_min_ver is defined and fzf_ver is not defined

    - name: Compare installed and desired Fzf versions.
      shell: |
        {{ ver_comp_func }}
        vercomp '{{ fzf_curr_ver.stdout }}' '{{ fzf_ver }}'
      args:
        executable: /usr/bin/bash
      changed_when: false
      failed_when: false
      register: compare_result
      when: fzf_ver is defined

  when: fzf_curr_ver.rc == 0 and (fzf_ver is defined or fzf_min_ver is defined)

- block:
    - block:
        - name: Clone Fzf repository from GitHub.
          git:
            repo: https://github.com/junegunn/fzf.git
            dest: ~/.fzf
            version: master

      rescue:
        - name: Remove local Fzf repo directory in case of cloning failure.
          file:
            path: ~/.fzf
            state: absent

        - name: Try to cleanly clone the Fzf repository after a failed attempt.
          git:
            repo: https://github.com/junegunn/fzf.git
            dest: ~/.fzf
            version: master

    - name: Define desired version in the install script.
      lineinfile:
        dest: ~/.fzf/install
        regexp: '^version='
        line: 'version={{ fzf_ver }}'
        state: present
        backup: false
      when: fzf_ver is defined

    - name: Install Fzf.
      command: ~/.fzf/install --all

  when: >
    fzf_curr_ver.rc !=0 or
    (compare_min_result.rc is defined and compare_min_result.rc == 2) or
    (compare_result.rc is defined and compare_result.rc != 0)
