---
- name: Ensure the ~/.local/bin directory exists.
  file:
    path: ~/.local/bin
    state: directory
    mode: 0755

- name: Rsync version-compare script.
  ansible.posix.synchronize:
    src: '{{ playbook_dir }}/src/version-compare.sh'
    dest: ~/.local/bin/version-compare
    archive: true
    checksum: true
  register: result
  changed_when: >
    not result.stdout_lines == [] and
    not (result.stdout_lines | length == 1 and
    result.stdout_lines[0] == '.d..t...... ./')
  delegate_to: localhost
