---
- name: Get key(s) to declare.
  set_fact:
    declare_keys: "{{ declare_keys|default([]) + [ lookup('file', item) ] }}"
  with_items:
    - "~/.ssh/{{ ssh_key_filename }}.pub"

- name: Declare authorized key(s).
  ignore_unreachable: true
  ansible.posix.authorized_key:
    user: 'user'
    state: present
    key: "{{ declare_keys | join('\n') }}"
    exclusive: true
