---
# Install Docker-compose v2
- name: Copy version-compare script.
  include_role:
    name: copy-scripts

- name: Check Docker-compose v2 version.
  shell: set -o pipefail && docker compose version | \
    egrep -o "([0-9]{1,}\.)+[0-9]{1,}"
  args:
    executable: /usr/bin/bash
  changed_when: false
  failed_when: false
  register: dk_compose_curr_ver

- name: Compare installed and desired Docker-compose versions.
  command: ~/.local/bin/version-compare \
    '{{ dk_compose_curr_ver.stdout }} {{ docker_compose_ver }}'
  changed_when: false
  failed_when: false
  register: compare_result
  when: dk_compose_curr_ver.rc == 0

- block:
    - name: Create a ~/.docker/cli-plugins directory if it does not exist.
      file:
        path: ~/.docker/cli-plugins
        state: directory
        mode: 0755

    - name: Download Docker-compose binary.
      get_url:
        url: "https://github.com/docker/compose/releases/download/\
          v{{ docker_compose_ver }}/docker-compose-linux-x86_64"
        dest: ~/.docker/cli-plugins/docker-compose
        mode: 0755
        force: true

  when: dk_compose_curr_ver.rc !=0 or compare_result.rc != 0
