---
- name: Check if VBoxService already installed.
  command: /usr/sbin/VBoxService --version
  changed_when: false
  failed_when: false
  register: check_vboxservice

- block:
    - name: Get the CDROM mountpoint status.
      stat:
        path: /media/cdrom
      register: vbox_guest_additions_dirstatus

    - name: Create the CDROM mountpoint.
      file:
        path: /media/cdrom
        state: directory
        mode: 0755
      when: vbox_guest_additions_dirstatus.stat.exists is false
      become: true

    - name: Mount CDROM read-only.
      ansible.posix.mount:
        path: /media/cdrom
        src: /dev/cdrom
        fstype: iso9660
        opts: ro,noauto
        state: mounted
      become: true

    - name: Determine kernel version.
      command: uname -r
      changed_when: false
      register: vbox_guest_additions_kernel_version

    - name: Install VBox Guest Additions dependencies.
      apt:
        name:
          - dkms
          - build-essential
          - linux-headers-generic
          - 'linux-headers-{{ vbox_guest_additions_kernel_version.stdout }}'
        state: present
      become: true

    - name: Install VBoxLinuxAdditions.
      shell: cd /media/cdrom || exit 1; ./VBoxLinuxAdditions.run
      failed_when: false
      become: true

  when: check_vboxservice.rc != 0
