---
- name: Update and upgrade apt packages.
  apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400   # One day
  when: ansible_os_family == 'Debian'

- name: Update and upgrade yum packages (exclude kernel).
  yum:
    name: '*'
    state: latest
    exclude: kernel*
    update_cache: true
  when: ansible_os_family == 'RedHat'
