---
- name: Ensure the ~/.local/bin directory exists.
  file:
    path: ~/.local/bin
    state: directory
    mode: 0755

- name: Rsync version-compare script.
  ansible.posix.synchronize:
    src: '{{ playbook_dir }}/src/version-compare.sh'
    dest: ~/.local/bin/version-compare
    archive: true
    checksum: true
  register: version_compare_script_sync_result
  changed_when: >
    not version_compare_script_sync_result.stdout_lines == []
    and not (version_compare_script_sync_result.stdout_lines | length == 1
    and version_compare_script_sync_result.stdout_lines[0] == '.d..t...... ./')
  delegate_to: localhost
