---
# Install compose-switch

- name: Check Docker-compose v2 version.
  command: docker compose version
  changed_when: false
  failed_when: false
  register: compose_v2

- block:
    - name: Check if Compose-switch is installed.
      command: compose-switch version
      changed_when: false
      failed_when: false
      register: compose_switch

    - block:
        - name: Filter desired Compose-switch version.
          set_fact:
            desired_ver: '{{ compose_switch_ver |
              regex_search("[0-9]{1,}(\.[0-9]{1,}){0,2}") }}'
          when: compose_switch_ver is defined

        - block:
            - name: Ensure pip3 is installed.
              apt:
                name: python3-pip
                state: present
              become: true

            - name: Ensure required python module is installed.
              pip:
                name: github3.py

            - name: Get latest release tag.
              community.general.github_release:
                user: docker
                repo: compose-switch
                action: latest_release
              register: latest_release

            - name: Filter release number.
              set_fact:
                latest_release_tag: '{{ latest_release.tag |
                  regex_search("([0-9]{1,}\.)+[0-9]{1,}") }}'

          when: compose_switch_ver is not defined

        - name: Define release number.
          set_fact:
            release_num: '{{ desired_ver if (desired_ver is defined)
              else latest_release_tag }}'

        - name: Download Compose-switch binary.
          get_url:
            url: "https://github.com/docker/compose-switch/releases/download/\
              v{{ release_num }}/docker-compose-linux-amd64"
            dest: "{{ compose_switch_path | default('/usr/local/bin') }}/\
              compose-switch"
            mode: 0755
            force: true
          become: true

      when: >
        compose_switch.rc != 0
        or (update_apps is defined
        and ('all' in update_apps or 'compose-switch' in update_apps))

    - name: Check if Docker-compose v1 is installed.
      shell: set -o pipefail && type docker-compose | cut -d\  -f3
      args:
        executable: /usr/bin/bash
      changed_when: false
      failed_when: false
      register: compose_v1

    - block:
        - name: Check Docker-compose v1 version.
          shell: >
            set -o pipefail && docker-compose --version |
            grep -Eo "[0-9]{1,}(\.[0-9]{1,}){0,}" | head -n1
          args:
            executable: /usr/bin/bash
          changed_when: false
          failed_when: false
          register: compose_1_ver

        - name: Check if Docker-compose is not Compose-switch.
          set_fact:
            compose_1_is_not_switch: ''
          when: compose_1_ver.rc == 0 and compose_1_ver.stdout
            is version('2.0.0', '<', version_type='strict')

        - block:
            - name: Ensure alternative copy of docker-compose v1 is absent.
              file:
                path: '{{ compose_v1.stdout }}-1'
                state: absent
              become: true

            - name: Rename docker-compose v1.
              command:
                cmd: 'mv {{ compose_v1.stdout }} {{ compose_v1.stdout }}-1'
              args:
                creates: '{{ compose_v1.stdout }}-1'
                removes: '{{ compose_v1.stdout }}'
              become: true

            - name: "Define renamed docker-compose-1 as an alternative for
                docker-compose command."
              community.general.alternatives:
                name: docker-compose
                link: '{{ compose_v1.stdout }}'
                path: '{{ compose_v1.stdout }}-1'
                priority: 1
              become: true

          when: compose_1_is_not_switch is defined

      when: compose_v1.rc == 0

    - name: Define the default docker-compose path if v1 is not found in PATH.
      set_fact:
        compose_v1_path: /usr/local/bin/docker-compose
      when: compose_v1.rc != 0

    - name: Define compose-switch as an alternative for docker-compose command.
      community.general.alternatives:
        name: docker-compose
        link: '{{ compose_v1_path | default(compose_v1.stdout) }}'
        path: "{{ compose_switch_path | default('/usr/local/bin') }}/\
          compose-switch"
        priority: 99
      become: true

  when: compose_v2.rc ==0
