---
- name: Update and optionally upgrade apt packages.
  apt:
    upgrade: false
    update_cache: true
    cache_valid_time: 86400   # One day
  become: true

- name: Install VBox Guest Additions if was not installed from bootstrap play.
  include_role:
    name: remote-user-key-based-access
    tasks_from: vbox-guest-additions.yaml
  when: vbox_guest is defined

- name: Install apt packages.
  apt:
    name:
      - cmake
      - curl
      - fasd
      - gcc
      - gettext
      - net-tools
      - nfs-kernel-server
      - python3-pip
      - unzip
      - wmctrl
      - xclip
      - xdotool
      - zsh
    state: present
  become: true
