---
- import_playbook: bootstrap.yaml

- name: Main playbook
  hosts: all
  remote_user: '{{ user_keybase }}'
  gather_facts: true
  vars:
    user_keybase: admin

  roles:
    - role: ../../submodules/ansible-role-docker
      # docker_package: docker-ce=5:20.10.12~3-0~ubuntu-focal   # latest if N/D.
      docker_install_compose: false
      docker_users: ['{{ user_keybase }}']

    - role: ../../submodules/ansible-role-kubernetes
      kubernetes_packages:
        - name: kubelet
          state: present
        - name: kubectl
          state: present
        - name: kubeadm
          state: present
        - name: kubernetes-cni
          state: present
      kubernetes_version: '1.20'
      # kubernetes_version_rhel_package: '1.20.4'
      # kubernetes_role: master   # set up for each node in the inventory file
      kubernetes_kubeadm_kubelet_config_file_path: "/etc/kubernetes/\
      kubeadm-kubelet-config.yaml"
      kubernetes_config_init_configuration:
        localAPIEndpoint:
          advertiseAddress: "{{ kubernetes_apiserver_advertise_address |
          default(ansible_default_ipv4.address, true) }}"
      kubernetes_config_cluster_configuration:
        networking:
          podSubnet: "{{ kubernetes_pod_network.cidr }}"
        kubernetesVersion: "{{ kubernetes_version_kubeadm }}"
      kubernetes_config_kubelet_configuration:
        cgroupDriver: cgroupfs
      kubernetes_config_kube_proxy_configuration: {}
      # kubernetes_config_kubelet_configuration: ""
      # kubernetes_kubelet_extra_args: ""
      kubernetes_kubelet_extra_args_config_file: /etc/default/kubelet
      kubernetes_kubeadm_init_extra_opts: ""
      kubernetes_join_command_extra_opts: "--ignore-preflight-errors=Swap"
      kubernetes_allow_pods_on_master: false
      kubernetes_pod_network:
      # Flannel CNI.
      cni: 'flannel'
      cidr: '10.244.0.0/16'
      #
      # Calico CNI.
      # cni: 'calico'
      # cidr: '192.168.0.0/16'
      #
      # Weave CNI.
      # cni: 'weave'
      # cidr: '192.168.0.0/16'
