---
- name: Ensure required dependencies are installed.
  apt:
    name:
      - python3-pip
      - zsh
    state: present
  become: true

- name: Setup Zsh as user default shell.
  user:
    name: '{{ ansible_user }}'
    shell: /usr/bin/zsh
  become: true

- name: Ensure ~/.zshrc and ~/.zshenv files exist.
  file:
    path: '~/{{ item }}'
    state: touch
    mode: 0644
    access_time: preserve
    modification_time: preserve
  with_items: ['.zshrc', '.zshenv']

- name: Initial setup of Zsh shell.
  command: ssh -q -o BatchMode=yes -o ConnectTimeout=3 \
    '{{ ansible_user }}@{{ ansible_host }}' "source ~/.zshrc && echo OK"
  delegate_to: localhost
  changed_when: false

- name: Checkout kubectx Zsh plugin to non-buggy commit.
  git:
    repo: https://github.com/ahmetb/kubectx.git
    dest: ~/.oh-my-zsh/custom/plugins/kubectx/kubectx
    version: a50965728886c753031f687114c516651963141b
    refspec: +refs/heads/*:refs/remotes/origin/*

- name: Install gnupg module for the Ranger encryption/decryption functions.
  pip:
    name: gnupg

- name: Add language settings to ~/.zshenv to suppress the Ranger locale error.
  blockinfile:
    path: ~/.zshenv
    block: |
      export LANGUAGE="en_US.UTF-8"
      export LC_ALL="en_US.UTF-8"
    state: present
    backup: false

- name: Set timezone to '{{ timezone }}'.
  community.general.timezone:
    name: '{{ timezone }}'
  when: timezone is defined
  become: true
