---
- name: Copy dotfiles.
  include_role:
    name: copy-dotfiles

- name: Ensure that Zsh is installed.
  package:
    name:
      - zsh
    state: present

- name: Setup Zsh as user default shell.
  user:
    name: "{{ user_keybase }}"
    shell: /usr/bin/zsh
  become: true

- name: Check if ~/.zshrc already exists.
  stat:
    path: "~/.zshrc"
  register: filestat

- name: Create ~/.zshrc file if it doesn't exist.
  file:
    path: "~/.zshrc"
    state: touch
    mode: "0644"
  when: filestat.stat.exists is false

- name: Initial setup of Zsh shell.
  command: ssh -q -o BatchMode=yes -o ConnectTimeout=3 \
    "{{ user_keybase }}"@"{{ ansible_host }}" "source ~/.zshrc && echo OK"
  delegate_to: localhost
  changed_when: false

- name: Checkout kubectx Zsh plugin to non-buggy commit.
  git:
    repo: https://github.com/ahmetb/kubectx.git
    dest: "~/.oh-my-zsh/custom/plugins/kubectx/kubectx"
    version: "a50965728886c753031f687114c516651963141b"
    refspec: '+refs/heads/*:refs/remotes/origin/*'
