---
# Install Docker-compose v2

- name: Create a ~/.local/bin directory if it does not exist.
  file:
    path: ~/.local/bin
    state: directory
    mode: 0755

- name: Rsync version_compare script.
  ansible.posix.synchronize:
    src: '{{ playbook_dir }}/src/version_compare.sh'
    dest: ~/.local/bin/version_compare
    archive: true
    checksum: true
  register: result
  changed_when: >
    not result.stdout_lines == [] and
    not (result.stdout_lines | length == 1 and
    result.stdout_lines[0] == '.d..t...... ./')
  delegate_to: localhost

- name: Check Docker-compose v2 version.
  shell: set -o pipefail && docker compose version | \
    egrep -o "([0-9]{1,}\.)+[0-9]{1,}"
  args:
    executable: /usr/bin/bash
  changed_when: false
  failed_when: false
  register: dk_compose_curr_ver

- name: Compare installed and desired Docker-compose versions.
  command: ~/.local/bin/version_compare \
    '{{ dk_compose_curr_ver.stdout }} {{ docker_compose_ver }}'
  changed_when: false
  failed_when: false
  register: compare_result
  when: dk_compose_curr_ver.rc == 0

- block:
    - name: Create a ~/.docker/cli-plugins directory if it does not exist.
      file:
        path: ~/.docker/cli-plugins
        state: directory
        mode: 0755

    - name: Download Docker-compose binary.
      get_url:
        url: "https://github.com/docker/compose/releases/download/\
          v{{ docker_compose_ver }}/docker-compose-linux-x86_64"
        dest: ~/.docker/cli-plugins/docker-compose
        mode: 0755
        force: true

  when: dk_compose_curr_ver.rc !=0 or compare_result.rc != 0
