---
- name: Update and optionally upgrade apt packages.
  apt:
    upgrade: false
    update_cache: true
    cache_valid_time: 86400   # One day
  become: true

- name: Install VBox Guest Additions if was not installed from bootstrap play.
  include_role:
    name: remote-user-key-based-access
    tasks_from: vbox-guest-additions.yaml
  when: vbox_guest is defined

- name: Install packages.
  apt:
    name:
      - cmake
      - curl
      - fasd
      - gcc
      - gettext
      - net-tools
      - nfs-kernel-server
      - python3-pip
      - unzip
      - wmctrl
      - xclip
      - xdotool
      - zsh
    state: present  # packages with non-critical version
  become: true

# Install latest Git
- include_tasks: git.yaml

# Install Vim from sources
- include_tasks: vim.yaml

# Install Neovim from sources
- include_tasks: neovim.yaml

# Install Tmux from sources
- include_tasks: tmux.yaml

# Install Ranger from sources
- include_tasks: ranger.yaml
