---
# Install latest Neovim from sources

- name: Check Neovim version.
  shell: set -o pipefail && nvim --version | head -n 1 | \
    egrep -o "([0-9]{1,}\.[0-9]{1,})"
  args:
    executable: /usr/bin/bash
  changed_when: false
  failed_when: false
  register: nvim_ver

- name: DEBUG
  debug:
    var: nvim_ver
  when: debug_mode is defined

- block:
    - name: Ensure Neovim dependencies are installed.
      apt:
        name:
          - cmake
        state: present
      become: true

    - name: Create a build directory if it does not exist.
      file:
        path: ~/build
        state: directory
        mode: 0755

    - name: Clone Neovim repository from GitHub.
      git:
        repo: https://github.com/neovim/neovim.git
        dest: ~/build/neovim
        version: "{{ nvim_specific_ver | default('master') }}"

    - name: Compile and install Neovim.
      shell: cd ~/build/neovim/ && make && sudo make install

  when: nvim_ver.rc !=0 or nvim_ver.stdout | float < nvim_minimum_ver
