---
# Install latest Vim from sources with lua support

- name: Check Neovim version.
  shell: set -o pipefail && tmux -V | egrep -o "([0-9]{1,}\.[0-9]{1,})"
  args:
    executable: /usr/bin/bash
  changed_when: false
  failed_when: false
  register: check_tmux_version

- name: DEBUG
  debug:
    var: check_tmux_version
  when: debug_mode is defined

- block:
    - name: Install Tmux dependencies.
      package:
        name:
          - libevent-dev
          - autoconf
          - automake
          - pkg-config
          - bison
        state: present

    - name: Create a build directory if it does not exist.
      file:
        path: "/home/{{ username_access_key }}/build"
        state: directory
        mode: '0755'
      become: false

    - name: Clone Tmux repository from GitHub.
      git:
        repo: https://github.com/tmux/tmux.git
        dest: "/home/{{ username_access_key }}/build/tmux"
        version: "{{ tmux_specific_version | default('master') }}"
      become: false

    - name: Configure Tmux.
      shell: cd /home/"{{ username_access_key }}"/build/tmux/ || exit 1; \
        ./autogen.sh && ./configure
      args:
        executable: /usr/bin/bash
      become: false

    - name: Compile Tmux using make.
      shell: cd /home/"{{ username_access_key }}"/build/tmux/ && \
        make
      become: false

    - name: Install compiled Tmux using make install.
      shell: cd /home/"{{ username_access_key }}"/build/tmux/ && \
        make install

  when: >
    check_tmux_version.rc !=0 or
    check_tmux_version.stdout | float < tmux_minimum_version
