---
# Install latest Vim from sources with lua support

- name: Check Vim version.
  shell: set -o pipefail && vim --version | head -n 1 | cut -d\  -f5
  args:
    executable: /usr/bin/bash
  changed_when: false
  failed_when: false
  register: check_vim_version

- name: DEBUG
  debug:
    var: check_vim_version
  when: debug_mode is defined

- name: Check Vim features.
  shell: set -o pipefail && vim --version | sed -n -e '/^\(+\|-\)/p'
  args:
    executable: /usr/bin/bash
  changed_when: false
  failed_when: false
  register: check_vim_features

- name: DEBUG
  debug:
    var: check_vim_features
  when: debug_mode is defined

- name: Check Vim features.
  shell: set -o pipefail && vim --version | tail -n +5
  args:
    executable: /usr/bin/bash
  changed_when: false
  failed_when: false
  register: check_vim_features

- block:
    - name: Install Vim dependencies.
      package:
        name:
          - gcc
          - liblua5.3-dev
          - xorg-dev
        state: present

    - name: Create lua links.
      file:
        src: '/usr/include/lua5.3/{{ item.src }}'
        dest: '/usr/include/{{ item.dest }}'
        state: link
      loop:
        - {src: lua.h, dest: lua.h}
        - {src: luaconf.h, dest: luaconf.h}
        - {src: lualib.h, dest: lualib.h}
        - {src: lauxlib.h, dest: lauxlib.h}

    - name: Create lua links.
      file:
        src: /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0
        dest: /usr/lib/liblua.so
        state: link

    - name: Create a build directory if it does not exist.
      file:
        path: "/home/{{ username_access_key }}/build"
        state: directory
        mode: '0755'
      become: false

    - name: Clone Vim repository from GitHub.
      git:
        repo: https://github.com/vim/vim.git
        dest: "/home/{{ username_access_key }}/build/vim"
        version: "{{ vim_specific_version | default('master') }}"
      become: false

    - name: Configure Vim.
      shell: cd /home/"{{ username_access_key }}"/build/vim/ || exit 1; \
        ./configure \
        --enable-multibyte \
        --with-features=huge \
        --enable-luainterp=dynamic \
        --enable-python3interp=dynamic \
        --enable-cscope \
        --enable-gui=auto \
        --enable-fontset \
        --enable-largefile \
        --disable-netbeans \
        --with-x \
        --enable-fail-if-missing
      args:
        executable: /usr/bin/bash
      become: false

    - name: Compile Vim using make.
      shell: cd /home/"{{ username_access_key }}"/build/vim/ && \
        make
      args:
        executable: /usr/bin/bash
      become: false

    - name: Install compiled Vim using make install.
      shell: cd /home/"{{ username_access_key }}"/build/vim/ && \
        make install
      args:
        executable: /usr/bin/bash

  when: >
    check_vim_version.rc !=0 or
    check_vim_version.stdout | float < vim_minimum_version or
    not "+clipboard" in check_vim_features.stdout or
    not "+xterm_clipboard" in check_vim_features.stdout
