---
- name: 'get key(s) to declare'
  set_fact:
    declare_keys: "{{ declare_keys|default([]) + [ lookup('file', item) ] }}"
  with_items:
    - "/home/andrei/.ssh/id_rsa_ubuntu-vm.pub"

- name: 'deploy SSH public key'
  ignore_unreachable: true
  ansible.posix.authorized_key:
    user: 'user'
    state: present
    key: "{{ declare_keys | join('\n') }}"
    exclusive: true
