---
- name: Rsync dotfiles (Zsh, Vim, Tmux).
  ansible.posix.synchronize:
    src: '{{ playbook_dir }}/dotfiles/'
    dest: ~/
    archive: true
    checksum: true
    rsync_opts:
      - "--prune-empty-dirs"  # to sync only included files
      - "--include='.vimrc'"
      - "--include='.zshrc'"
      - "--include='.p10k.zsh'"
      - "--include='.tmux.conf'"
      - "--include='.tmux.conf.local'"
      - "--include='*/'"      # to sync only included files
      - "--exclude='*'"       # to sync only included files
  delegate_to: localhost

- name: Create a ~/.config/nvim directory if it does not exist.
  file:
    path: ~/.config/nvim
    state: directory
    mode: 0755

- name: Create link to ~/.vimrc for Neovim.
  file:
    src: '~/.vimrc'
    dest: '~/.config/nvim/init.vim'
    state: link

- name: Rsync dotfiles (Ranger).
  ansible.posix.synchronize:
    src: '{{ playbook_dir }}/dotfiles/ranger'
    dest: ~/.config/
    checksum: true
    recursive: true
    rsync_opts:
      - "--exclude='*.pyc'"
      - "--delete"
  register: ranger_files
  delegate_to: localhost

- block:
    - name: Create a .local/bin directory if it does not exist.
      file:
        path: ~/.local/bin
        state: directory
        mode: 0755

    - name: Collect list of all Ranger scripts.
      find:
        paths: ~/.config/ranger/scripts/
      register: find

    - name: Create links for all Ranger scripts.
      file:
        src: '{{ item.path }}'
        path: '~/.local/bin/{{ item.path | basename }}'
        state: link
      with_items: '{{ find.files }}'
  when: ranger_files.changed
