---
- name: Copy dotfiles.
  copy:
    src: '{{ playbook_dir }}/dotfiles/{{ item.src }}'
    dest: '/home/{{ user_keybase }}/{{ item.dest }}'
    owner: '{{ user_keybase }}'
    group: '{{ user_keybase }}'
    mode: 0644
  loop:
    - {src: .vimrc, dest: .vimrc}
    - {src: .zshrc, dest: .zshrc}
    - {src: .p10k.zsh, dest: .p10k.zsh}
    - {src: .tmux.conf, dest: .tmux.conf}
    - {src: .tmux.conf.local, dest: .tmux.conf.local}
    - {src: ranger, dest: .config}

- name: Create a .local/bin directory if it does not exist.
  file:
    path: '/home/{{ user_keybase }}/.local/bin'
    state: directory
    mode: '0755'
  become: false

- name: Collect list of all Ranger scripts.
  find:
    paths: "/home/{{ user_keybase }}/.config/ranger/scripts/"
  register: find

- name: Create links for all Ranger scripts.
  file:
    src: "{{ item.path }}"
    path: "/home/{{ user_keybase }}/.local/bin/{{ item.path | basename }}"
    state: link
  with_items: "{{ find.files }}"

- name: Ensure that desired shell is installed.
  package:
    name:
      - zsh
    state: present

- name: Change user default shell.
  user:
    name: "{{ user_keybase }}"
    shell: /usr/bin/zsh
