---
# Install Vim from sources with lua support

- name: Check if Vim is an alias.
  shell: set -o pipefail && command -v vim | cut -d=  -f1
  args:
    executable: /usr/bin/bash
  changed_when: false
  failed_when: false
  register: vim_command

- name: Unalias Vim.
  command: unalias vim
  changed_when: false
  failed_when: false
  when: vim_command.stdout == 'alias vim'

- name: Check Vim version.
  shell: >
    set -o pipefail && vim --version |
    sed -n 1,2p | grep -Eo "(([0-9]{1,}\.)+[0-9]{1,}|-[0-9]+)" |
    tr -d '\n' | tr - .
  args:
    executable: /usr/bin/bash
  changed_when: false
  failed_when: false
  register: vim_curr_ver

- name: DEBUG
  debug:
    var: vim_curr_ver
  when: debug_mode is defined

- name: Check Vim features.
  shell: set -o pipefail && vim --version | sed -n -e '/^\(+\|-\)/p'
  args:
    executable: /usr/bin/bash
  changed_when: false
  failed_when: false
  register: vim_features

- name: DEBUG
  debug:
    var: vim_features
  when: debug_mode is defined

- block:
    - name: Import a variable containing a Bash script to compare versions.
      include_role:
        name: version-compare-function

    - name: Compare installed and min Vim versions.
      shell: |
        {{ ver_comp_func }}
        vercomp '{{ vim_curr_ver.stdout }}' '{{ vim_min_ver }}'
      args:
        executable: /usr/bin/bash
      changed_when: false
      failed_when: false
      register: compare_min_result
      when: vim_min_ver is defined and vim_ver is not defined

    - name: Compare installed and desired Vim versions.
      shell: |
        {{ ver_comp_func }}
        vercomp '{{ vim_curr_ver.stdout }}' '{{ vim_ver }}'
      args:
        executable: /usr/bin/bash
      changed_when: false
      failed_when: false
      register: compare_result
      when: vim_ver is defined

  when: vim_curr_ver.rc == 0 and (vim_ver is defined or vim_min_ver is defined)

- block:
    - name: Ensure Vim dependencies are installed.
      apt:
        name:
          - gcc
          - liblua5.3-dev
          - xorg-dev
        state: present
      become: true

    - name: Ensure lua links exist.
      file:
        src: '/usr/{{ item.src }}'
        dest: '/usr/{{ item.dest }}'
        state: link
      loop:
        - {src: include/lua5.3/lua.h, dest: include/lua.h}
        - {src: include/lua5.3/luaconf.h, dest: include/luaconf.h}
        - {src: include/lua5.3/lualib.h, dest: include/lualib.h}
        - {src: include/lua5.3/lauxlib.h, dest: include/lauxlib.h}
        - {src: lib/x86_64-linux-gnu/liblua5.3.so.0.0.0, dest: lib/liblua.so}
      become: true

    - block:
        - name: Ensure the ~/build directory exists.
          file:
            path: ~/build
            state: directory
            mode: 0755

        - name: Clone Vim repository from GitHub.
          git:
            repo: https://github.com/vim/vim.git
            dest: ~/build/vim
            version: "{{ vim_ver | default('master') }}"

      rescue:
        - name: Remove local Vim repo directory in case of cloning failure.
          file:
            path: ~/build/vim
            state: absent

        - name: Try to cleanly clone the Vim repository after a failed attempt.
          git:
            repo: https://github.com/vim/vim.git
            dest: ~/build/vim
            version: "{{ vim_ver | default('master') }}"

    - name: Configure Vim.
      shell: cd ~/build/vim/ || exit 1; \
        ./configure \
        --enable-multibyte \
        --with-features=huge \
        --enable-luainterp=dynamic \
        --enable-python3interp=dynamic \
        --enable-cscope \
        --enable-gui=auto \
        --enable-fontset \
        --enable-largefile \
        --disable-netbeans \
        --with-x \
        --enable-fail-if-missing

    - name: Compile and install Vim.
      shell: cd ~/build/vim/ && make clean && make && sudo make install

  when: >
    vim_curr_ver.rc !=0
    or (compare_min_result.rc is defined and compare_min_result.rc == 2)
    or (compare_result.rc is defined and compare_result.rc != 0)
    or not "+clipboard" in vim_features.stdout
    or not "+xterm_clipboard" in vim_features.stdout
