---
all:
  vars:
    ansible_user: vagrant

  children:
    master:
      hosts:
        k8s-master:
          ansible_host: 192.168.100.151
          ansible_port: 22
          ansible_ssh_private_key_file: >-
            ./.vagrant/machines/k8s-master/virtualbox/private_key
          kubernetes_role: "master"
    workers:
      vars:
        ansible_port: 22
        kubernetes_role: "node"
      hosts:
        k8s-node-1:
          ansible_host: 192.168.100.161
          ansible_ssh_private_key_file: >-
            ./.vagrant/machines/k8s-node-1/virtualbox/private_key
        k8s-node-2:
          ansible_host: 192.168.100.162
          ansible_ssh_private_key_file: >-
            ./.vagrant/machines/k8s-node-2/virtualbox/private_key
