---
- import_playbook: bootstrap.yaml

- name: Main playbook
  hosts: all
  remote_user: '{{ user_keybase }}'
  gather_facts: true

  roles:
    - role: copy-dotfiles
      dotfiles_path: '{{ lookup("env", "GIT_DOTFILES") }}'
    - role: environment-setup
    - role: install-apt-packages
    - role: git-apt
    - role: kubectl-apt
    - role: vim
    - role: neovim
    - role: tmux
    - role: ranger
    - role: ansible-role-docker
      docker_install_compose: true
      docker_compose_version: 1.29.2
      docker_users: ['{{ user_keybase }}']
      docker_daemon_options:
        exec-opts:
          - native.cgroupdriver=systemd
        log-driver: json-file
        log-opts:
          max-size: 100m
        storage-driver: overlay2
      become: true
    - role: docker-compose-v2
    - role: compose-switch
    - role: exa
    - role: node
