---
- import_playbook: bootstrap.yaml

- name: Main playbook
  hosts: all
  become: true
  remote_user: '{{ user_keybase }}'
  gather_facts: true

  roles:
    - role: install-packages
    - role: copy-dotfiles
    - role: setup-zsh
