---
- hosts: servers
  # gather_facts: false
  ignore_unreachable: true
  roles:
    - role: create-remote-user
      vars:
        - ansible_user: '{{ username_pass_access }}'
        - ansible_password: '{{ userpass_pass_access }}'
        - ansible_become_pass: '{{ userpass_pass_access }}'

    - role: key-based-ssh-access
      vars:
        - ansible_user: '{{ username_pass_access }}'
        - ansible_password: '{{ userpass_pass_access }}'
        - ansible_become_pass: '{{ userpass_pass_access }}'
