---
- import_playbook: bootstrap.yaml

- name: Main playbook
  hosts: all
  remote_user: '{{ user_keybase }}'
  gather_facts: true

  roles:
    - role: copy-dotfiles
    - role: environment-setup
    - role: install-apt-packages
    - role: git-apt
    - role: kubectl-apt
    - role: vim
    - role: neovim
    - role: tmux
    - role: ranger
    - role: ansible-role-docker
      become: true
    - role: docker-compose-v2
    - role: compose-switch
