---
- import_playbook: bootstrap.yaml

- name: Main playbook
  hosts: all
  remote_user: '{{ user_keybase }}'
  gather_facts: true

  roles:
    - role: install-packages
    - role: environment-setup
    - role: ansible-role-docker
      become: true
