---
- name: Update and optionally upgrade apt packages.
  apt:
    upgrade: false
    update_cache: true
    cache_valid_time: 86400   # One day
  become: true

- name: Install apt packages.
  apt:
    name:
      - cmake
      - curl
      - fasd
      - gcc
      - gettext
      - net-tools
      - nfs-kernel-server
      - python3-pip
      - unzip
      - wmctrl
      - xclip
      - xdotool
      - zsh
    state: present
  become: true
