---
- name: Check if local ~/.ssh directory exists.
  ansible.builtin.stat:
    path: "~/.ssh"
  register: ssh_directory_exists_check

- name: DEBUG
  ansible.builtin.debug:
    var: ssh_directory_exists_check
  when: debug_mode is defined

- name: Check if needed os tools exist.
  ansible.builtin.command: which sshpass ssh-keygen ssh-copy-id
  register: os_tools_exist
  ignore_errors: true
  changed_when: false

- name: Stop execution if any of the needed os tools is missing.
  ansible.builtin.fail:
    msg: "one or more of the: sshpass, ssh-keygen, ssh-copy-id are missing on \
    this machine. please install them using the method recommended for your \
    distribution before proceeding."
  when: os_tools_exist.rc != 0

- name: Create ~/.ssh local directory.
  ansible.builtin.file:
    path: "~/.ssh"
    state: directory
    mode: "0700"
  register: ssh_directory_creation
  when: >
    ssh_directory_exists_check is defined and
    ssh_directory_exists_check.stat.exists is false

- name: DEBUG
  ansible.builtin.debug:
    var: ssh_directory_creation
  when: debug_mode is defined

- name: Check if .ssh key pair exists.
  ansible.builtin.stat:
    path: "~/.ssh/{{ item }}"
  register: ssh_key_file_exists_check
  with_items:
    - "{{ ssh_key_filename }}"
    - "{{ ssh_key_filename }}.pub"

- name: DEBUG
  ansible.builtin.debug:
    var: ssh_key_file_exists_check.results[1].stat.exists
  when: debug_mode is defined

- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa).
  community.crypto.openssh_keypair:
    path: ~/.ssh/{{ ssh_key_filename }}
  register: ssh_key_creation
  when: >
    ssh_key_file_exists_check is defined and
    (ssh_key_file_exists_check.results[0].stat.exists is false or
    ssh_key_file_exists_check.results[1].stat.exists is false)

- name: DEBUG
  ansible.builtin.debug:
    var: ssh_key_creation
  when: debug_mode is defined

- name: Check if ~/.ssh/config file exists.
  ansible.builtin.stat:
    path: "~/.ssh/config"
  register: ssh_config_file_exists_check

- name: DEBUG
  ansible.builtin.debug:
    var: ssh_config_file_exists_check
  when: debug_mode is defined

- name: Create the ~/.ssh/config file.
  ansible.builtin.file:
    path: "~/.ssh/config"
    state: touch
    mode: "0644"
  register: ssh_config_file_creation
  when: >
    ssh_config_file_exists_check is defined and
    ssh_config_file_exists_check.stat.exists is false

- name: Add the new ssh key to the ~/.ssh/config file.
  ansible.builtin.lineinfile:
    path: "~/.ssh/config"
    line: "identityfile ~/.ssh/{{ ssh_key_filename }}"
    state: present
    backup: true
  register: ssh_config_file_key_addition

- name: DEBUG
  ansible.builtin.debug:
    var: ssh_config_file_key_addition
  when: debug_mode is defined
