---
- name: Add Git repository.
  apt_repository:
    repo: ppa:git-core/ppa
    state: present
    update_cache: true
  become: true
  register: repo

- block:
    - name: Install latest Git.
      apt:
        name:
          - git
        state: present
      become: true
  when: repo.changed
