---
# Install Gitflow

- name: Check Gitflow version.
  shell: >
    set -o pipefail && \. ~/.profile ; git-flow version |
    grep -Eo "[0-9]{1,}(\.[0-9]{1,}){0,}" | head -n1
  args:
    executable: /usr/bin/bash
  changed_when: false
  failed_when: false
  register: gitflow_curr_ver

- name: Filter current version stdout.
  set_fact:
    current_ver: '{{ gitflow_curr_ver.stdout |
      regex_search("[0-9]{1,}(\.[0-9]{1,}){0,2}") }}'
  when: gitflow_curr_ver.rc == 0

- name: Filter desired Gitflow version.
  set_fact:
    desired_ver: '{{ gitflow_ver |
      regex_search("[0-9]{1,}(\.[0-9]{1,}){0,2}") }}'
  when: gitflow_ver is defined

- block:
    - block:
        - name: Ensure the ~/build directory exists.
          file:
            path: ~/build
            state: directory
            mode: 0755

        - name: Clone Gitflow repository from GitHub.
          git:
            repo: https://github.com/nvie/gitflow.git
            dest: ~/build/gitflow
            version: "{{ desired_ver | default('develop') }}"

      rescue:
        - name: Remove local Gitflow repo directory in case of cloning failure.
          file:
            path: ~/build/gitflow
            state: absent

        - name: 'Try to cleanly clone the Gitflow repository after a failed
            attempt.'
          git:
            repo: https://github.com/nvie/gitflow.git
            dest: ~/build/gitflow
            version: "{{ desired_ver | default('develop') }}"

    - name: Ensure the installation path directory exists.
      file:
        path: "{{ gitflow_path | default('$HOME/.local') }}"
        state: directory
        mode: 0755

    - name: Get directory status.
      stat:
        path: "{{ gitflow_path | default('$HOME/.local') }}"
      register: dirstatus

    - name: Install Gitflow.
      shell: >
        cd ~/build/gitflow/ &&
        {{ 'sudo' if dirstatus.stat.writeable is false }}
        make prefix={{ gitflow_path | default('~/.local') }} install

    - name: Ensure the Gitflow install path is in the system PATH.
      lineinfile:
        dest: '{{ item }}'
        line: "[[ \":$PATH:\" != *\":{{ gitflow_path |
          default('$HOME/.local') }}/bin:\"* ]] && export PATH=\"$PATH:\
          {{ gitflow_path | default('$HOME/.local') }}/bin\""
        state: present
        backup: false
      with_items:
        - ~/.profile
        - ~/.bashrc
        - ~/.zshenv
      failed_when: false

  when: >
    gitflow_curr_ver.rc !=0
    or (desired_ver is defined
    and current_ver is version(desired_ver, '!=', version_type='strict'))
    or (update_apps is defined
    and ('all' in update_apps or 'gitflow' in update_apps))
