---
# Install Exa

- name: Check Exa version.
  shell: >
    set -o pipefail && ~/.exa/bin/exa --version | sed -n 2p |
    grep -Eo "[0-9]{1,}(\.[0-9]{1,}){0,}" | head -n1
  args:
    executable: /usr/bin/bash
  changed_when: false
  failed_when: false
  register: exa_curr_ver

- block:
    - name: Import a variable containing a Bash script to compare versions.
      include_role:
        name: version-compare-function

    - name: Compare installed and desired Exa versions.
      shell: |
        {{ ver_comp_func }}
        vercomp '{{ exa_curr_ver.stdout }}' '{{ exa_ver }}'
      args:
        executable: /usr/bin/bash
      changed_when: false
      failed_when: false
      register: compare_result

  when: exa_curr_ver.rc == 0 and exa_ver is defined

- block:
    - name: Filter release number.
      set_fact:
        release_num: '{{ exa_ver | regex_search("([0-9]{1,}\.)+[0-9]{1,}") }}'
      when: exa_ver is defined

    - block:
        - name: Ensure pip3 is installed.
          apt:
            name: python3-pip
            state: present
          become: true

        - name: Ensure required python module is installed.
          pip:
            name: github3.py

        - name: Get latest release tag.
          community.general.github_release:
            user: ogham
            repo: exa
            action: latest_release
          register: latest_release

        - name: Filter release number.
          set_fact:
            release_num: '{{ latest_release |
              regex_search("([0-9]{1,}\.)+[0-9]{1,}") }}'

      when: exa_ver is not defined

    - name: Ensure the ~/.exa directory exists.
      file:
        path: ~/.exa
        state: directory
        mode: 0755

    - name: 'Download and extract the archive
        exa-linux-x86_64-musl-v{{ release_num }}.zip.'
      unarchive:
        src: "https://github.com/ogham/exa/releases/download/\
          v{{ release_num }}/exa-linux-x86_64-musl-v{{ release_num }}.zip"
        dest: ~/.exa
        remote_src: true

  when: >
    exa_curr_ver.rc !=0
    or (compare_result.rc is defined and compare_result.rc != 0)
