---
# Install Neovim from sources

- name: Check Neovim version.
  shell: >
    set -o pipefail && nvim --version | head -n 1 |
    grep -Eo "[0-9]{1,}(\.[0-9]{1,}){0,}" | head -n1
  args:
    executable: /usr/bin/bash
  changed_when: false
  failed_when: false
  register: nvim_curr_ver

- name: Filter current version stdout.
  set_fact:
    nvim_current_ver: '{{ nvim_curr_ver.stdout |
    regex_search("[0-9]{1,}(\.[0-9]{1,}){0,2}") }}'
  when: nvim_curr_ver.rc == 0

- name: Filter min Neovim version.
  set_fact:
    nvim_minimum_ver: '{{ nvim_min_ver |
    regex_search("[0-9]{1,}(\.[0-9]{1,}){0,2}") }}'
  when: nvim_min_ver is defined and nvim_ver is not defined

- name: Filter desired Neovim version.
  set_fact:
    nvim_desired_ver: '{{ nvim_ver |
    regex_search("[0-9]{1,}(\.[0-9]{1,}){0,2}") }}'
  when: nvim_ver is defined

- name: DEBUG
  debug:
    var: nvim_curr_ver
  when: debug_mode is defined

- block:
    - name: Ensure Neovim dependencies are installed.
      apt:
        name:
          - cmake
          - gettext
        state: present
      become: true

    - name: Ensure the ~/build directory exists.
      file:
        path: ~/build
        state: directory
        mode: 0755

    - block:
        - name: Clone Neovim repository from GitHub.
          git:
            repo: https://github.com/neovim/neovim.git
            dest: ~/build/neovim
            version: "{{ 'v' + nvim_desired_ver if nvim_desired_ver is defined
            else 'master' }}"
            force: true

      rescue:
        - name: Remove local Neovim repo directory in case of cloning failure.
          file:
            path: ~/build/neovim
            state: absent

        - name: >
            Try to cleanly clone the Neovim repository after a failed attempt.
          git:
            repo: https://github.com/neovim/neovim.git
            dest: ~/build/neovim
            version: "{{ 'v' + nvim_desired_ver if nvim_desired_ver is defined
            else 'master' }}"

    - name: Ensure the /usr/local/include/sys directory exists.
      file:
        path: /usr/local/include/sys
        state: directory
        mode: 0755
      become: true

    - name: Ensure reqired links exist.
      file:
        src: '/usr/include/{{ item.src }}'
        dest: '/usr/local/include/{{ item.dest }}'
        state: link
      loop:
        - {src: endian.h, dest: sys/endian.h}
      become: true

    - name: Compile and install Neovim.
      shell: cd ~/build/neovim/ && make && sudo make install

  when: >
    nvim_curr_ver.rc !=0
    or (nvim_minimum_ver is defined and nvim_desired_ver is not defined
    and nvim_current_ver is
    version(nvim_minimum_ver, '<', version_type='strict'))
    or (nvim_desired_ver is defined
    and nvim_current_ver is
    version(nvim_desired_ver, '!=', version_type='strict'))
    or (update_apps is defined and ('all' in update_apps
    or 'nvim' in update_apps or 'neovim' in update_apps))
