---
# Install Ranger (filemanager) from sources

- name: Check Ranger version.
  shell: >
    set -o pipefail && ranger --version | head -n1 |
    grep -Eo "([0-9]{1,}(\.[0-9]{1,}){0,}|ranger-master)" | head -n1
  args:
    executable: /usr/bin/bash
  changed_when: false
  failed_when: false
  register: ranger_curr_ver

- block:
    - name: Import a variable containing a Bash script to compare versions.
      include_role:
        name: version-compare-function

    - name: Compare installed and min Ranger versions.
      shell: |
        {{ ver_comp_func }}
        vercomp '{{ ranger_curr_ver.stdout }}' '{{ ranger_min_ver }}'
      args:
        executable: /usr/bin/bash
      changed_when: false
      failed_when: false
      register: compare_min_result
      when: >
        ranger_curr_ver.stdout != 'ranger-master' and ranger_min_ver is defined
        and ranger_ver is not defined

    - name: Compare installed and desired Ranger versions.
      shell: |
        {{ ver_comp_func }}
        vercomp '{{ ranger_curr_ver.stdout }}' '{{ ranger_ver }}'
      args:
        executable: /usr/bin/bash
      changed_when: false
      failed_when: false
      register: compare_result
      when: ranger_curr_ver.stdout != 'ranger-master' and ranger_ver is defined

  when: >
    ranger_curr_ver.rc == 0
    and (ranger_ver is defined or ranger_min_ver is defined)

- name: DEBUG
  debug:
    var: ranger_curr_ver
  when: debug_mode is defined

- block:
    - name: Ensure the ~/build directory exists.
      file:
        path: ~/build
        state: directory
        mode: 0755

    - block:
        - name: Clone Ranger repository from GitHub.
          git:
            repo: https://github.com/ranger/ranger.git
            dest: ~/build/ranger
            version: "{{ ranger_ver | default('master') }}"

      rescue:
        - name: Remove local Ranger repo directory in case of cloning failure.
          file:
            path: ~/build/ranger
            state: absent

        - name: >
            Try to cleanly clone the Ranger repository after a failed attempt.
          git:
            repo: https://github.com/ranger/ranger.git
            dest: ~/build/ranger
            version: "{{ ranger_ver | default('master') }}"

    - name: Install Ranger.
      shell: cd ~/build/ranger/ && sudo make install

  when: >
    ranger_curr_ver.rc !=0
    or (compare_min_result.rc is defined and compare_min_result.rc == 2)
    or (compare_result.rc is defined and compare_result.rc != 0)
