---
# Install latest Ranger (filemanager) from sources

- name: Check Ranger version.
  command: ranger --version
  changed_when: false
  failed_when: false
  register: ranger_ver

- name: DEBUG
  debug:
    var: ranger_ver
  when: debug_mode is defined

- block:
    - name: Ensure the ~/build directory exists.
      file:
        path: ~/build
        state: directory
        mode: 0755

    - name: Clone Ranger repository from GitHub.
      git:
        repo: https://github.com/ranger/ranger.git
        dest: ~/build/ranger
        version: "{{ ranger_ver | default('master') }}"

    - name: Install Ranger.
      shell: cd ~/build/ranger/ && sudo make install

  when: ranger_ver.rc !=0
